Add dependent build to test

diff --git a/.github/workflows/workflow.yml b/.github/workflows/workflow.yml
--- a/.github/workflows/workflow.yml
+++ b/.github/workflows/workflow.yml
@@ -9,8 +9,18 @@ jobs:
 
     steps:
       - name: fails
-        if: always() && false
-        run: echo "This is a failure"
-      - name: succeeds
-        if: always() && true
-        run: echo "This is a success"
+        run: exit 1
+
+  notification:
+    runs-on: ubuntu-latest
+
+    needs: build
+
+    steps:
+      - name: Slack Notify Failure
+        if: always() && (contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled'))
+        run: echo "Failure"
+
+      - name: Slack Notify Success
+        if: always() && !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled')
+        run: echo "Success"
